const projects = [
  {
    id: 1,
    name: "primary",
    desc: "simple color, shapes, and animation",
    info: "",
    technologies: "html | css | js | gsap",
    img: "",
    url: "https://su-t-primary.netlify.app/",
  },
  {
    id: 2,
    name: "real & true",
    desc: "artist portfolio",
    info: "",
    technologies: "html | css | js",
    img: "",
    url: "https://real-true-su-t.netlify.app/",
  },
  {
    id: 3,
    name: "float",
    desc: "dreamy text animation",
    info: "",
    technologies: "html | css | js | gsap",
    img: "",
    url: "https://su-t-float.netlify.app/",
  },
  {
    id: 4,
    name: "stornoway",
    desc: "construction company",
    info: "",
    technologies: "html | css | js",
    img: "",
    url: "https://stornoway-su-t.netlify.app/",
  },
  {
    id: 5,
    name: "you are",
    desc: "positive text animation",
    info: "",
    technologies: "html | css | js | gsap",
    img: "",
    url: "https://su-t-you-are.netlify.app/",
  },
  {
    id: 6,
    name: "poveda",
    desc: "Travel Agency Site",
    info: "",
    technologies: "html | css | js",
    img: "",
    url: "https://poveda-su-t.netlify.app/",
  },
  {
    id: 7,
    name: "valla table",
    desc: "Thai Cuisine Elevated",
    info: "",
    technologies: "html | css | js",
    img: "",
    url: "https://valla-table-su-t.netlify.app/",
  },
  {
    id: 8,
    name: "bloc camp",
    desc: "Music Venue Application",
    info: "",
    technologies: "react | mongodb | express | node",
    img: "",
    url: "https://the-bloc-camp.onrender.com/",
  },
];
