const projects = [
  {
    id: 1,
    name: "Real&True",
    desc: "Artist Portfolio",
    info: "",
    technologies: "html | css | js",
    img: "",
    url: "https://real-true-su-t.netlify.app/",
  },
  {
    id: 2,
    name: "Stornoway",
    desc: "Architect Firm",
    info: "",
    technologies: "html | css | js",
    img: "",
    url: "https://stornoway-su-t.netlify.app/",
  },
  {
    id: 3,
    name: "Jiffy",
    desc: "Meme Generator",
    info: "",
    technologies: "html | css | js | giphy api",
    img: "",
    url: "https://sutheedev-jiffy.netlify.app/",
  },
  {
    id: 4,
    name: "valla table",
    desc: "Thai Cuisine Elevated",
    info: "",
    technologies: "html | css | js",
    img: "",
    url: "https://valla-table-su-t.netlify.app/",
  },
  {
    id: 5,
    name: "TodayTask",
    desc: "To-do-list",
    info: "",
    technologies: "react | typescript | vitejs",
    img: "",
    url: "https://su-t-today-task.netlify.app/",
  },
  {
    id: 6,
    name: "poveda",
    desc: "Travel Agency",
    info: "",
    technologies: "react | style-components",
    img: "",
    url: "https://poveda.onrender.com/",
  },
  {
    id: 7,
    name: "bloc camp",
    desc: "Venue Application",
    info: "",
    technologies: "react | mongodb | express | node",
    img: "",
    url: "https://the-bloc-camp.onrender.com/",
  },
];
